Repository SU-SWS/vpue_undergrad_subtheme, pull requests merged in 2021-07, with the labels that each got.

#7 Ue 289 variant set up
  dist/assets/png/StanfordUndergradDiamond_LC.png
  dist/assets/png/StanfordUndergrad_Diamond_CB.png
  dist/assets/png/icon-search--white.png
  dist/css/vpue-undergrad.css
  src/assets/png/StanfordUndergradDiamond_LC.png
  src/assets/png/StanfordUndergrad_Diamond_CB.png
  src/assets/png/icon-search--white.png
  src/js/vpue_undergrad_subtheme.behaviors.js
  src/scss/components/hero-banner/_hero-banner.scss
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/components/hero-banner/index.scss
  src/scss/components/index.scss
  src/scss/config/index.scss
  src/scss/theme/_main-navigation.scss
  src/scss/theme/index.scss
  src/scss/utilities/mixins/_links.scss
  src/scss/utilities/mixins/index.scss
  src/scss/utilities/variables/_colors.scss
  templates/components/hero-banner/card.html.twig
  templates/components/hero-banner/pattern-hero--variant-front.html.twig
  vpue_undergrad_subtheme.libraries.yml
  vpue_undergrad_subtheme.react_behaviors.yml
  vpue_undergrad_subtheme.theme
Labels: size/m

#9 UE-286: responsive work.
  dist/assets/png/StanfordUndergrad_Diamond_LC.png
  dist/assets/svg/caret-down-white.svg
  dist/css/vpue-undergrad.css
  src/assets/png/StanfordUndergrad_Diamond_LC.png
  src/scss/components/hero-banner/_hero-banner.scss
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/utilities/mixins/_links.scss
  vpue_undergrad_subtheme.theme
Labels: size/s

#6 UE-258: Undergrad Subtheme Basic Header
  dist/assets/png/icon-search--plum.png
  dist/css/vpue-undergrad.css
  dist/js/scripts.js
  dist/templates/decanter/components/accordion/accordion.twig
  dist/templates/decanter/components/alert/alert.twig
  dist/templates/decanter/components/brand-bar/brand-bar.twig
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/main-nav/main-nav.twig
  dist/templates/decanter/components/media/media.twig
  dist/templates/decanter/components/quote/quote.twig
  dist/templates/decanter/components/site-search/site-search.twig
  src/assets/png/icon-search--plum.png
  src/scss/components/brand-bar/_brand-bar.scss
  src/scss/components/brand-bar/index.scss
  src/scss/components/index.scss
  src/scss/components/main-nav/_main-nav.scss
  src/scss/components/main-nav/index.scss
  src/scss/components/search-bar/_search-bar.scss
  src/scss/components/search-bar/index.scss
  templates/components/brand-bar/vpue--brand-bar.html.twig
  templates/page.html.twig
Labels: size/s

#8 UE-273: Revisions for fat footer
  dist/css/vpue-undergrad.css
  src/scss/base/_base-fonts.scss
  src/scss/components/fat-footer/_footer--column-one.scss
  src/scss/components/fat-footer/_footer--links-buttons.scss
  src/scss/components/fat-footer/_footer.scss
  src/scss/theme/_main-navigation.scss
  templates/components/fat-footer/vpue-fat-footer.html.twig
Labels: size/s

#10 UE-284: fixing the z-indexes and the banner alignment
  dist/assets/svg/StanfordUndergrad_logo.svg
  dist/assets/svg/Stanford_Cardinal.svg
  dist/assets/svg/Stanford_White.svg
  dist/assets/svg/Undergrad_Black.svg
  dist/assets/svg/Undergrad_White.svg
  dist/css/vpue-undergrad.css
  dist/js/scripts.js
  dist/templates/decanter/components/accordion/accordion.twig
  dist/templates/decanter/components/alert/alert.twig
  dist/templates/decanter/components/brand-bar/brand-bar.twig
  dist/templates/decanter/components/global-footer/global-footer.twig
  dist/templates/decanter/components/local-footer/local-footer.twig
  dist/templates/decanter/components/main-nav/main-nav.twig
  dist/templates/decanter/components/media/media.twig
  dist/templates/decanter/components/quote/quote.twig
  dist/templates/decanter/components/site-search/site-search.twig
  src/assets/svg/StanfordUndergrad_logo.svg
  src/assets/svg/Stanford_Cardinal.svg
  src/assets/svg/Stanford_White.svg
  src/assets/svg/Undergrad_Black.svg
  src/assets/svg/Undergrad_White.svg
  src/scss/components/hero-banner/_hero-banner.scss
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/components/main-nav/_main-nav.scss
  src/scss/components/search-bar/_search-bar.scss
  src/scss/theme/_main-navigation.scss
  src/scss/theme/index.scss
  templates/block--system-branding-block.html.twig
  vpue_undergrad_subtheme.theme
Labels: size/l

#12 Ue 311 logo line
  dist/assets/svg/close-white.svg
  dist/assets/svg/hamburger-white.svg
  dist/css/vpue-undergrad.css
  src/scss/components/hero-banner/_hero-banner.scss
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/components/main-nav/_main-nav.scss
Labels: size/xs

#11 UE-313: hero fixes
  dist/css/vpue-undergrad.css
  src/scss/components/hero-banner/_hero-banner.scss
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/components/main-nav/_main-nav.scss
  templates/block--system-branding-block.html.twig
Labels: size/xs

#13 UE-313: fixup the hover
  dist/css/vpue-undergrad.css
  src/scss/components/hero-banner/_hero-banner.scss
Labels: size/xs

#14 UE-301 - Inline headings and Big Red list
  dist/css/vpue-undergrad.css
  src/scss/components/hero-banner/_hero-banner.scss
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/theme/_wysiwyg.scss
  src/scss/theme/index.scss
Labels: size/xs

#15 UE-325: fixing the logo alignment and mobile logo issue
  dist/css/vpue-undergrad.css
  src/scss/components/hero-banner/_navigation-white.scss
  src/scss/components/main-nav/_main-nav.scss
Labels: size/xs
